name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/**.md'
jobs:
  run-parse-server-ci:
    name: CI of Parse Server ${{ matrix.version }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['5.6.0', '6.3.1']
    steps:
    - name: Checkout parse-server ${{ matrix.version }}
      uses: actions/checkout@v2
      with:
        repository: parse-community/parse-server
        ref: ${{ matrix.version }}
        path: parse-server
    - name: cd to Parse Server
      run: cd parse-server; ls
#    - name: Run CI workflow of Parse Server
#      run: npm run test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
