name: ci
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/**.md'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
  run-parse-server-ci:
    name: CI of Parse Server ${{ matrix.version }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['5.6.0', '6.3.1']
    steps:
    - name: Checkout parse-server ${{ matrix.version }}
      uses: actions/checkout@v2
      with:
        repository: parse-community/parse-server
        ref: ${{ matrix.version }}
        path: parse-server
    # - name: Run CI workflow of Parse Server
    #   uses: actions/github-script@v6
    #   with:
        # script: |
        #   const fs = require('fs');
        #   const yaml = require('js-yaml');
        #   const path = './parse-server/.github/workflows/ci.yml';
        #   const ciConfig = yaml.load(fs.readFileSync(path, 'utf8'));
        #   console.log(ciConfig);
        #   return ciConfig;

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
