name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/**.md'
jobs:
  run-parse-server-ci:
    name: CI of Parse Server 
    timeout-minutes: 60
    runs-on: macos-latest
    strategy:
      matrix:
#        version: ['5.6.0', '6.3.1']
         version: ['alpha']
    steps:
    - name: Checkout parse-server ${{ matrix.version }}
      uses: actions/checkout@v2
      with:
        repository: ddrechse/parse-server
        ref: realDBAdapterLoader
        path: parse-server
    - name: Create Oracle Storage Adapter Dir
      run: mkdir parse-server/src/Adapters/Storage/Oracle;
           ls -la parse-server/src/Adapters/Storage/Oracle;
    - name: Checkout Oracle Storage Adapter
      uses: actions/checkout@v2
      with:
        repository: oracle-samples/oracleadapter-parse
        ref: ''
        path: parse-server/src/Adapters/Storage/Oracle
    - name: Validate Oracle Dir
      run: ls -la parse-server/src/Adapters/Storage/Oracle; 
    - name: Install Java 11
      run: java -version;
           wget https://download.oracle.com/java/17/latest/jdk-17_macos-x64_bin.tar.gz;
           gunzip jdk-17_macos-x64_bin.tar.gz;
           chmod 777 jdk-17_macos-x64_bin.tar;
           tar -xf jdk-17_macos-x64_bin.tar;
           export PATH=${PWD}/jdk-17.0.10.jdk/Contents/Home/bin:$PATH;
           echo $PATH;
           java --version;
    - name: Install Sqlcl
      run: wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-23.3.0.270.1251.zip;
           echo $JAVA_HOME;
           export JAVA_HOME=${PWD}/jdk-17.0.10.jdk/Contents/Home;
           echo $JAVA_HOME;
           unzip sqlcl-23.3.0.270.1251.zip;
           ./sqlcl/bin/sql -V;
    - name: Install Docker
      run: brew install docker;
           colima start;
#            brew install --cask docker;
#           open -a docker && while ! docker info > /dev/null 2>&1; do sleep 1 ; done
#           docker info;
#           open /Applications/Docker.app;
#           docker info;
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true           
