name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/**.md'
jobs:
  run-parse-server-ci:
    name: CI of Parse Server ${{ matrix.version }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['5.6.0', '6.3.1']
    steps:
    - name: Checkout parse-server ${{ matrix.version }}
      uses: actions/checkout@v2
      with:
        repository: parse-community/parse-server
        ref: ${{ matrix.version }}
        path: parse-server
    - name: Create Oracle Storage Adapter Dir
      run: mkdir parse-server/src/Adapters/Storage/Oracle;
           ls -la parse-server/src/Adapters/Storage/Oracle;
           docker info;
    - name: Checkout Oracle Storage Adapter
      uses: actions/checkout@v2
      with:
        repository: oracle-samples/oracleadapter-parse
        ref: ''
        path: parse-server/src/Adapters/Storage/Oracle
    - name: Validate Oracle Dir
      run: ls -la parse-server/src/Adapters/Storage/Oracle;
    - name: Run Tests
      run: cd parse-server; 
           npm install; 
           npm run test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
