name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/**.md'
jobs:
  run-parse-server-ci:
    name: CI of Parse Server ${{ matrix.version }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['5.6.0', '6.3.1']
    steps:
    - name: Checkout parse-server ${{ matrix.version }}
      uses: actions/checkout@v2
      with:
        repository: parse-community/parse-server
        ref: ${{ matrix.version }}
        path: parse-server
    - name: Create Oracle Storage Adapter Dir
      run: mkdir parse-server/src/Adapters/Storage/Oracle;
           ls -la parse-server/src/Adapters/Storage/Oracle;
    - name: Checkout Oracle Storage Adapter
      uses: actions/checkout@v2
      with:
        repository: oracle-samples/oracleadapter-parse
        ref: ''
        path: parse-server/src/Adapters/Storage/Oracle
    - name: Validate Oracle Dir
      run: ls -la parse-server/src/Adapters/Storage/Oracle;
    - name: Install Sqlcl
      run: wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-23.3.0.270.1251.zip;
           unzip sqlcl-23.3.0.270.1251.zip;
           ./sqlcl/bin/sql -V;
    - name: Install Instant Client
      run: uname -m;
           ls -la /lib;
           ls -al /lib/libc*;
           wget https://download.oracle.com/otn_software/linux/instantclient/2113000/instantclient-basic-linux.x64-21.13.0.0.0dbru.zip;
           unzip instantclient-basic-linux.x64-21.13.0.0.0dbru.zip;
    - name: Run Free23c
      run: docker run --name free23c -d -p 1521:1521 -e ORACLE_PWD=Welcome12345 container-registry.oracle.com/database/free:latest;
           docker ps -a;
    - name: Wait for container
      run: sleep 120;
           docker ps -a;
           ./sqlcl/bin/sql -V;
    - name: Enable SODA in image
      run: echo "alter session set container=FREEPDB1;grant db_developer_role to pdbadmin;grant soda_app to pdbadmin;GRANT UNLIMITED TABLESPACE TO pdbadmin;quit;" > soda;
           cat soda;
           ./sqlcl/bin/sql sys/Welcome12345@localhost:1521/free as sysdba @./soda
    - name: Run Tests
      run: cd parse-server; 
           npm install; 
           npm run test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
